# .github/workflows/main.yml
on: [push, pull_request]

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    name: Norminette 42
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
    - uses: JaeSeoKim/norminette-action@v3
      with:
        flags: '.'
