# .github/workflows/main.yml
on:
  push:
    paths-ignore:
      - 'main.c'
  pull_request:
    paths-ignore:
      - 'main.c'

jobs:
  norminette_job:
    runs-on: ubuntu-latest
    name: norminette
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v3
      with:
        flags: '.'

